name: Continuous Integration

# This action works with pull requests and pushes
# This action works with ALL branches
on:
  push:
    paths:
      - ".github/workflows/**"
      - "president-of-the-world-frontend/**"
  pull_request:
    paths:
      - ".github/workflows/**"
      - "president-of-the-world-frontend/**"

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: president-of-the-world-frontend/
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: president-of-the-world-frontend/package-lock.json
      - name: Install Dependencies
        run: npm install
      - name: ESLint
        run: npm run lint-total
      - name: Prettier
        run: npm run prettier-check
      - name: TypeScript Compiler
        run: npx tsc
        # Run Next Lint + TSC + BUILD
      - name: Next.js Build
        run: npm run build
